packages:
  - packages/*
  - apps/*
  - examples/*

allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  sharp: true

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs
  - sharp

peerDependencyRules:
  allowedVersions:
    tailwindcss: 4.x
    next: 16.x
