/**
 * @module playground/enterstellar/system-prompt
 * @description LLM system prompt builder for the Enterstellar Playground.
 *
 * Two distinct system prompts — one correct, one sabotaged.
 * Both accept the Scene definition to produce **multi-zone output**.
 *
 * **Correct prompt (healthy/cloud):**
 * - Full compact manifest (component names, descriptions, prop summaries)
 * - **Concrete prop schema examples** from `ComponentContract.examples[]`
 *   (addresses the manifest generator's loss of nested Zod structure)
 * - **Domain Data Context** — optional pre-queried dataset that simulates
 *   the `@enterstellar-ai/adapters DataAdapter.query()` pipeline. When present, the
 *   LLM uses this as ground truth instead of hallucinating domain data.
 * - Scene zone layout with expected components and intent hints
 * - Cross-zone coherence instructions ("data consistency across zones")
 * - Strict JSON array output format: `ZoneIntent[]`
 *
 * **Sabotaged prompt (hallucinating):**
 * - No manifest (LLM has zero knowledge of available components)
 * - No data context (LLM operates blind)
 * - Zone count only (no schemas, no tokens, no component names)
 * - Vague, loose output instructions
 * - Naturally produces the exact errors the compiler catches:
 *   invented names, wrong types, hardcoded CSS, missing fields
 *
 * @see implementation_plan.md §3.5 — System Prompt Design
 * @see implementation_plan.md §2.4 — Realistic Data Contexts
 * @see Design Choice R8 — compact JSON manifest format
 */


import type { CompactManifestEntry, ComponentContract } from '@enterstellar-ai/types';
import type { PlaygroundScene } from './scenes/types';


// ---------------------------------------------------------------------------
// Prompt Builders
// ---------------------------------------------------------------------------


/**
 * Builds the LLM system prompt for the given mode.
 *
 * @param manifest - Compact manifest entries from `generateManifest()`.
 *   Contains component names, descriptions, categories, and prop summaries.
 * @param scene - The active PlaygroundScene with zone definitions.
 * @param mode - The playground mode: `'healthy'`, `'cloud'`, or `'hallucinating'`.
 * @param contracts - Full component contracts for extracting example props.
 *   Required for healthy/cloud modes to inject concrete schema examples.
 * @param dataContext - Optional domain data context string (Markdown). When
 *   provided, injected into the correct prompt as ground-truth data that
 *   simulates the `@enterstellar-ai/adapters DataAdapter.query()` pipeline. The LLM
 *   uses this dataset instead of hallucinating domain-specific values.
 *   Sabotaged (hallucinating) prompts never receive data context.
 * @returns The complete system prompt string for the LLM.
 *
 * @example
 * ```ts
 * import { generateManifest } from '@enterstellar-ai/registry';
 * import { buildSystemPrompt } from './system-prompt';
 *
 * const manifest = generateManifest(contracts);
 * const prompt = buildSystemPrompt(manifest, activeScene, 'healthy', contracts, dataCtx);
 * ```
 */
export function buildSystemPrompt(
  manifest: readonly CompactManifestEntry[],
  scene: PlaygroundScene,
  mode: 'healthy' | 'cloud' | 'hallucinating',
  contracts?: readonly ComponentContract[],
  dataContext?: string,
): string {
  if (mode === 'hallucinating') {
    return buildSabotagedPrompt(scene);
  }
  return buildCorrectPrompt(manifest, scene, mode, contracts, dataContext);
}


// ---------------------------------------------------------------------------
// Correct Prompt (Healthy / Cloud)
// ---------------------------------------------------------------------------


/**
 * Builds the correct system prompt with full manifest and scene layout.
 *
 * The prompt instructs the LLM to:
 * 1. Fill each zone with an appropriate ComponentIntent
 * 2. Use ONLY components from the provided manifest
 * 3. Output a strict JSON array of ZoneIntent objects
 * 4. Maintain cross-zone data coherence
 *
 * **Prop Schema Examples (Critical):**
 * The compact manifest generated by `@enterstellar-ai/registry` flattens nested Zod
 * schemas to opaque type strings (e.g., `"columns": "array"` instead of
 * describing the inner `{ key: string, label: string }` shape). This causes
 * the LLM to hallucinate nested prop structures, producing schema validation
 * failures (ENS-3004) for components like DataTable, UserProfile, and
 * CommandPalette.
 *
 * The fix: inject concrete prop examples from `ComponentContract.examples[]`.
 * These are Zod-validated, production-quality prop objects that show the LLM
 * the exact structure expected — including nested arrays/objects.
 *
 * @param manifest - Compact registry manifest.
 * @param scene - Active scene with zone definitions.
 * @param mode - `'healthy'` or `'cloud'`.
 * @param contracts - Full component contracts for schema examples.
 * @param dataContext - Optional domain data context (Markdown).
 * @returns Complete system prompt string.
 *
 * @internal
 */
function buildCorrectPrompt(
  manifest: readonly CompactManifestEntry[],
  scene: PlaygroundScene,
  mode: 'healthy' | 'cloud',
  contracts?: readonly ComponentContract[],
  dataContext?: string,
): string {
  const manifestJson = JSON.stringify(manifest, null, 2);


  const zoneDescriptions = scene.zones
    .map((zone) => {
      const expected = zone.expectedComponent !== undefined
        ? ` (default: ${zone.expectedComponent}, override if user intent suggests a different component)`
        : '';
      return `  - Zone "${zone.name}"${expected}: ${zone.intentHint}`;
    })
    .join('\n');


  // Build concrete prop schema examples from contracts.
  // This compensates for the manifest generator's loss of nested Zod structure.
  const schemaExamples = contracts !== undefined
    ? buildSchemaExamples(contracts)
    : '';


  // Build the Domain Data Context section.
  // This simulates @enterstellar-ai/adapters DataAdapter.query() — the LLM receives
  // a pre-queried dataset as ground truth instead of hallucinating domain data.
  const dataContextSection = dataContext !== undefined
    ? `


## Domain Data Context (Ground Truth)


You have access to the following pre-queried enterprise dataset. This data simulates a production DataAdapter query. You MUST use this data as your primary source when generating component props — extract real names, amounts, statuses, dates, and metrics from the sections below. Do NOT invent data when it is available in this context.


${dataContext}
`
    : '';


  const cloudAddendum = mode === 'cloud'
    ? `\n\nIMPORTANT — CLOUD/FORGE MODE:
The user wants components that may NOT exist in the registry. If no registry component matches a zone's purpose, use "__forge__" as the component name and describe the desired UI in a "description" field within props. The Forge will generate a temporary component at runtime.`
    : '';


  return `You are an Enterstellar UI Agent. You receive a user's natural-language intent AND a Scene layout with ${String(scene.zones.length)} zone(s). Output a JSON array of ComponentIntent objects — one per zone.


The USER'S PROMPT is your primary input. The scene layout provides a default structure, but the user's prompt determines WHAT data and WHICH component best serves their request. If the user asks for something that fits a different component than the zone's default, use the better-fitting component.


## Available Components (Registry Manifest)


${manifestJson}
${schemaExamples}
${dataContextSection}
## Scene Layout


Scene: "${scene.name}" (${scene.category})
Zones:
${zoneDescriptions}


## Output Format


You MUST output a valid JSON array. Each element has these fields:
- "zone": string — MUST match one of the zone names above
- "component": string — MUST be a component name from the manifest above (PascalCase, exact match)
- "props": object — MUST conform to the component's prop schema. See the "Prop Schema Examples" section for exact structures.
- "confidence": number — your confidence score from 0.0 to 1.0


Example output for a 2-zone scene:
[
  { "zone": "zone-a", "component": "MetricCard", "props": { "label": "Revenue", "value": "$1.2M", "trend": "up" }, "confidence": 0.95 },
  { "zone": "zone-b", "component": "StatusBadge", "props": { "status": "online", "label": "API Healthy" }, "confidence": 0.9 }
]


## Rules


1. Output ONLY the JSON array. No markdown, no code fences, no explanation.
2. NEVER invent component names. Use ONLY names from the manifest.
3. NEVER output HTML, JSX, or CSS. Output only the JSON array.
4. NEVER use hardcoded color values (hex, rgb, oklch). The design token system handles colors.
5. Fill EVERY zone — output exactly ${String(scene.zones.length)} element(s) in the array.
6. Use realistic, domain-appropriate data that matches the scene's context.
7. You MUST provide EVERY single prop shown in the Prop Schema Examples unless it is specifically marked as '(optional)' in the manifest summary. Do NOT omit fields like 'status' or 'severity'. Missing required fields will cause a fatal compilation failure.
8. STRICT ENUMS: When a property is marked as 'enum: a|b|c' in the manifest, you MUST use one of those exact string values. DO NOT invent context-specific enum values (e.g., do not invent "stable" if the only valid options are "online" or "warning").
9. USER PROMPT PRIORITY: The user's prompt is the HIGHEST priority signal. If the user describes data that fits a different component than the zone's default, use the component that best matches the user's prompt. Zone defaults are fallbacks when the user's prompt is ambiguous. Always generate props with content that directly reflects the user's prompt — do NOT reuse generic/example data.
10. DATA CONTEXT PRIORITY: When a Domain Data Context is provided, you MUST populate component props with the actual data from the context. Use real entity names, real amounts, real statuses, and real dates from the dataset. Do NOT substitute generic or example data when the context provides specific values.


## Cross-Zone Coherence


The zones in this scene are part of the SAME dashboard. Ensure data consistency:
- If one zone shows heart rate (MetricCard), related zones should reference heart rate data (e.g., ActivityFeed showing "Vitals recorded")
- Use consistent naming, units, and time references across all zones
- Data should tell a coherent story — the dashboard should feel like a real application${cloudAddendum}`;
}


// ---------------------------------------------------------------------------
// Schema Examples Builder
// ---------------------------------------------------------------------------


/**
 * Builds a "Prop Schema Examples" section from component contracts.
 *
 * Extracts the first example from each contract and formats it as a
 * concrete JSON example the LLM can pattern-match against. This is
 * critical for components with nested array/object props where the
 * compact manifest's type summaries are too opaque.
 *
 * @param contracts - Full component contracts with validated examples.
 * @returns A formatted prompt section string, or empty string if no contracts.
 *
 * @internal
 */
function buildSchemaExamples(
  contracts: readonly ComponentContract[],
): string {
  if (contracts.length === 0) return '';


  const examples = contracts
    .filter((contract) => contract.examples.length > 0 && contract.name !== 'GenericCard')
    .map((contract) => {
      const example = contract.examples[0];
      if (!example) return ''; // Fallback, though our filter guarantees length > 0
      return `### ${contract.name}
\`\`\`json
${JSON.stringify(example.props, null, 2)}
\`\`\``;
    })
    .join('\n\n');


  return `


## Prop Schema Examples (REQUIRED structure for each component)


These are the EXACT prop structures expected by the compiler. For components with nested arrays/objects, every field shown is REQUIRED unless marked optional in the manifest.


${examples}


`;
}


// ---------------------------------------------------------------------------
// Sabotaged Prompt (Hallucinating)
// ---------------------------------------------------------------------------


/**
 * Builds the sabotaged system prompt — deliberately vague and schema-less.
 *
 * This prompt **omits the manifest entirely**, removing all knowledge of:
 * - Available component names
 * - Required prop schemas
 * - Design token conventions
 * - Valid enum values
 *
 * The result is that the LLM naturally produces hallucinated output:
 * invented component names, wrong prop types, hardcoded CSS values,
 * missing required fields. These are the exact errors the Enterstellar compiler
 * is designed to catch, demonstrating the value of type-safe GenUI.
 *
 * @param scene - Active scene (used only for zone count).
 * @returns Deliberately vague system prompt string.
 *
 * @internal
 */
function buildSabotagedPrompt(scene: PlaygroundScene): string {
  return `You are a helpful UI assistant. Output a JSON array describing UI components for a dashboard with ${String(scene.zones.length)} panel(s).


For each panel, output a JSON object with:
- "zone": a name for the panel (like "panel-1", "panel-2")
- "component": the name of a UI widget to display
- "props": an object with the widget's configuration
- "confidence": a number from 0 to 1


Use whatever component names and property values feel appropriate for the user's request. Be creative with the widget names and styling properties.


Output ONLY the JSON array. No explanation.`;
}
