/**
 * @module @enterstellar-ai/migration/assembly/assemble-test
 * @description Phase 3 — generates a `.test.ts` scaffold file from a
 * `StructuralManifest`.
 *
 * Produces a test file using `vitest` and `@enterstellar-ai/types` schema
 * validation that validates the generated contract. The test includes:
 * - Import of the generated contract
 * - `describe()` block with the component name
 * - `it()` test for contract schema validation (`ComponentContractSchema.parse()`)
 * - `it()` test for each example's props against the contract's props schema
 *
 * **Output is a string** — the assembled TypeScript test source code.
 * The caller writes it to disk (filesystem-agnostic).
 *
 * **L15 compliance:** Zero framework imports.
 *
 * @see Correction 1 — Phase 3 output: `.contract.ts` + `.test.ts`
 */

import type { StructuralManifest } from '../types.js';

// ---------------------------------------------------------------------------
// Test Assembly
// ---------------------------------------------------------------------------

/**
 * Assembles a `.test.ts` scaffold file from a `StructuralManifest`.
 *
 * Generates a minimal test file that imports the generated contract
 * and validates it using `ComponentContractSchema.parse()` from
 * `@enterstellar-ai/types`. The developer is expected to expand the tests with
 * additional assertions (accessibility, state rendering, etc.).
 *
 * The scaffold includes:
 * 1. **Contract schema validation** — ensures the exported contract
 *    satisfies `ComponentContractSchema` at runtime.
 * 2. **Example props validation** — ensures each example's props
 *    pass the contract's `props` schema.
 *
 * @param manifest - The `StructuralManifest` from Phase 1.
 * @param contractImportPath - Relative import path to the generated
 *   `.contract.ts` file (e.g., `'./PatientCard.contract'`).
 * @returns The assembled test file content as a TypeScript source string.
 *
 * @see Correction 1 — Phase 3 Assembly: Test Scaffold
 */
export function assembleTest(
    manifest: StructuralManifest,
    contractImportPath: string,
): string {
    const contractVarName = `${manifest.name}Contract`;

    const lines: string[] = [
        `/**`,
        ` * @module ${manifest.name}.test`,
        ` * @description Auto-generated test scaffold for the ${manifest.name} contract.`,
        ` *`,
        ` * This file was generated by the Enterstellar migration pipeline (Phase 3).`,
        ` * Expand with additional assertions as needed.`,
        ` *`,
        ` * @enterstellar-generated`,
        ` */`,
        ``,
        `import { describe, it, expect } from 'vitest';`,
        `import { ComponentContractSchema } from '@enterstellar-ai/types';`,
        `import { ${contractVarName} } from '${contractImportPath}';`,
        ``,
        `describe('${manifest.name} Contract', () => {`,
        `    it('satisfies ComponentContractSchema', () => {`,
        `        expect(() => ComponentContractSchema.parse(${contractVarName})).not.toThrow();`,
        `    });`,
        ``,
        `    it('has a valid name', () => {`,
        `        expect(${contractVarName}.name).toBe('${manifest.name}');`,
        `    });`,
        ``,
        `    it('has at least one tag', () => {`,
        `        expect(${contractVarName}.tags.length).toBeGreaterThanOrEqual(1);`,
        `    });`,
        ``,
        `    it('has at least one example', () => {`,
        `        expect(${contractVarName}.examples.length).toBeGreaterThanOrEqual(1);`,
        `    });`,
        ``,
        `    it('example props satisfy the props schema', () => {`,
        `        for (const example of ${contractVarName}.examples) {`,
        `            expect(() => ${contractVarName}.props.parse(example.props)).not.toThrow();`,
        `        }`,
        `    });`,
        ``,
        `    it('has all four lifecycle states', () => {`,
        `        expect(${contractVarName}.states.loading).toBeTruthy();`,
        `        expect(${contractVarName}.states.error).toBeTruthy();`,
        `        expect(${contractVarName}.states.empty).toBeTruthy();`,
        `        expect(${contractVarName}.states.ready).toBeTruthy();`,
        `    });`,
        ``,
        `    it('has accessibility configuration', () => {`,
        `        expect(${contractVarName}.accessibility.role).toBeTruthy();`,
        `        expect(${contractVarName}.accessibility.ariaLabel).toBeTruthy();`,
        `    });`,
        `});`,
        ``,
    ];

    return lines.join('\n');
}
