/**
 * @module @enterstellar-ai/contracts-shadcn/contracts
 * @description Barrel export for shadcn/ui component contracts.
 *
 * This directory is the target for the CI sync pipeline
 * (`sync-contracts-shadcn.yml`). The pipeline:
 *
 * 1. Scaffolds a temp Next.js project.
 * 2. Runs `npx shadcn@latest add --all` to install all components.
 * 3. Runs `enterstellar migrate` against the installed source files.
 * 4. Copies generated `*.contract.ts` files into this directory.
 * 5. Opens a human-gated PR with the updated contracts.
 *
 * **Pre-CI state:** `SHADCN_CONTRACTS` is an empty record. The type
 * infrastructure is in place so that `registerShadcnContracts()` can
 * operate against the record immediately when contracts arrive.
 *
 * **Post-CI state:** Each CI run adds/updates contract entries like:
 * ```ts
 * export const SHADCN_CONTRACTS = {
 *     Button: { name: 'Button', description: '...', props: z.object({...}), ... },
 *     Card:   { name: 'Card', description: '...', props: z.object({...}), ... },
 *     // ... ~50 components
 * } as const satisfies Record<string, ComponentContractInput>;
 * ```
 *
 * @see Correction 7 Decision 3 — CI Sync Pipeline
 * @see sync-contracts-shadcn.yml — workflow definition
 */

import type { ComponentContractInput } from '@enterstellar-ai/registry'; // Audit E1: from @enterstellar-ai/registry, NOT @enterstellar-ai/types

// ---------------------------------------------------------------------------
// Contract Record
// ---------------------------------------------------------------------------

/**
 * Master record of all shadcn/ui component contracts.
 *
 * **Current state:** Empty. Populated by the CI sync pipeline.
 *
 * Each key is a PascalCase component name (e.g., `'Button'`, `'Card'`).
 * Each value is a `ComponentContractInput` — the input to
 * `defineComponent()` from `@enterstellar-ai/registry`.
 *
 * When contracts exist, this record is used by:
 * - `registerShadcnContracts()` — to validate component maps and pair renderers.
 * - `ShadcnContractName` — derived literal union for type-safe keys.
 *
 * @see registerShadcnContracts — uses this record for validation + pairing
 * @see defineComponent — accepts each value as input
 */
export const SHADCN_CONTRACTS: Record<string, ComponentContractInput> = {
    // -------------------------------------------------------------------------
    // Populated by CI sync pipeline (sync-contracts-shadcn.yml).
    // Each entry is a defineComponent()-compatible contract input.
    //
    // DO NOT add entries manually — they are auto-generated by running
    // `enterstellar migrate` against upstream shadcn/ui source components.
    // -------------------------------------------------------------------------
};

// ---------------------------------------------------------------------------
// Derived Types
// ---------------------------------------------------------------------------

/**
 * Union type of all known shadcn/ui contract names.
 *
 * **Pre-CI:** Resolves to `string` (empty record → `string` keys).
 * **Post-CI:** Resolves to a literal union (e.g., `'Button' | 'Card' | ...`)
 * when the record is populated and typed with `as const satisfies`.
 *
 * Used by `ShadcnComponentMap` to provide compile-time key validation.
 */
export type ShadcnContractName = keyof typeof SHADCN_CONTRACTS;
