/**
 * @module @enterstellar-ai/compiler/nesting
 * @description Maximum nesting depth validation for `ComponentIntent` trees.
 *
 * Prevents stack overflows and DOM performance degradation from deeply nested
 * layout structures generated by malicious or buggy agents. The compiler walks
 * the intent tree and rejects any structure deeper than the configured limit.
 *
 * **L15 compliance:** Zero framework imports. Pure validation logic.
 *
 * @see Design Choice P4 — max 10 levels, configurable 3–20, error `ENS-2010`.
 */

import type { CompilationError } from '@enterstellar-ai/types';

import { maxNestingDepthError } from './errors.js';

// ---------------------------------------------------------------------------
// Nesting Validation Result
// ---------------------------------------------------------------------------

/**
 * Result of a nesting depth validation check.
 */
export type NestingValidationResult = {
    /** Whether the intent tree passes the depth check. */
    readonly valid: boolean;
    /** The maximum depth found in the intent tree. */
    readonly maxDepthFound: number;
    /** Error if depth exceeds the configured maximum. */
    readonly error?: CompilationError;
};

// ---------------------------------------------------------------------------
// Intent-like Shape
// ---------------------------------------------------------------------------

/**
 * Minimal shape of a value that could be a nested `ComponentIntent`.
 *
 * Used for recursive tree walking — the compiler checks if any prop value
 * looks like a nested intent (has `component` and `props` fields) and
 * counts it as a nesting level.
 */
type IntentLike = {
    readonly component: string;
    readonly props: Readonly<Record<string, unknown>>;
};

/**
 * Type guard: checks whether a value matches the minimal shape of a
 * nested `ComponentIntent` (has `component` string and `props` object).
 *
 * @param value - The value to check.
 * @returns `true` if the value looks like a nested intent.
 */
function isIntentLike(value: unknown): value is IntentLike {
    if (typeof value !== 'object' || value === null) {
        return false;
    }

    const obj = value as Record<string, unknown>;
    return (
        typeof obj['component'] === 'string' &&
        typeof obj['props'] === 'object' &&
        obj['props'] !== null
    );
}

// ---------------------------------------------------------------------------
// Recursive Depth Calculation
// ---------------------------------------------------------------------------

/**
 * Recursively calculates the maximum nesting depth of a props tree.
 *
 * Walks all prop values looking for nested intent-like structures.
 * Arrays are traversed element-by-element. Plain objects are checked
 * for the intent-like shape (`{ component, props }`).
 *
 * @param props - The props object to walk.
 * @param currentDepth - Current depth in the tree (starts at 1).
 * @returns The maximum depth found in the subtree.
 */
function calculateDepth(
    props: Readonly<Record<string, unknown>>,
    currentDepth: number,
): number {
    let maxDepth = currentDepth;

    for (const key of Object.keys(props)) {
        const value = props[key];

        if (isIntentLike(value)) {
            // Found a nested intent — recurse one level deeper
            const childDepth = calculateDepth(
                value.props,
                currentDepth + 1,
            );
            if (childDepth > maxDepth) {
                maxDepth = childDepth;
            }
        } else if (Array.isArray(value)) {
            // Check array elements for nested intents
            for (const element of value) {
                if (isIntentLike(element)) {
                    const childDepth = calculateDepth(
                        element.props,
                        currentDepth + 1,
                    );
                    if (childDepth > maxDepth) {
                        maxDepth = childDepth;
                    }
                }
            }
        }
        // Primitive values and non-intent objects: no nesting increase
    }

    return maxDepth;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Validates that a `ComponentIntent`'s prop tree does not exceed the
 * configured maximum nesting depth.
 *
 * The root intent counts as depth 1. Each nested intent-like structure
 * within props adds one level. The check is applied to the entire tree,
 * including deeply nested arrays of intents.
 *
 * @param props - The props object from the `ComponentIntent`.
 * @param maxNestingDepth - The configured maximum depth (default: 10, range: 3–20).
 * @returns A `NestingValidationResult` with the depth found and any error.
 *
 * @see Design Choice P4 — `ENS-2010: MAX_NESTING_DEPTH_EXCEEDED`.
 *
 * @example
 * ```ts
 * const result = validateNestingDepth(intent.props, 10);
 * if (!result.valid) {
 *   context.errors.push(result.error!);
 * }
 * ```
 */
export function validateNestingDepth(
    props: Readonly<Record<string, unknown>>,
    maxNestingDepth: number,
): NestingValidationResult {
    // Root intent is depth 1
    const maxDepthFound = calculateDepth(props, 1);

    if (maxDepthFound > maxNestingDepth) {
        return {
            valid: false,
            maxDepthFound,
            error: maxNestingDepthError(maxDepthFound, maxNestingDepth),
        };
    }

    return {
        valid: true,
        maxDepthFound,
    };
}
