/**
 * @module @enterstellar-ai/types/contract
 * @description ComponentContract — the canonical data shape for registering
 * a component in the Enterstellar ecosystem.
 *
 * A `ComponentContract` is pure data: schema, metadata, accessibility, and
 * design tokens. It has **no `render` field** — rendering is handled by
 * platform-specific renderer packages (`@enterstellar-ai/react`, `@enterstellar-ai/render-native`, etc.)
 * per Design Choice R6.
 *
 * @see Bible §3.1
 * @see Design Choices R1–R20, T1, T5, T9, T11
 */

import { z } from 'zod';

import type { ComponentId } from './brands.js';

// ---------------------------------------------------------------------------
// String Union Types
// ---------------------------------------------------------------------------

/**
 * Predefined component categories.
 * Extensible via `custom:{name}` prefix for domain-specific categories.
 *
 * @see Design Choice R11
 */
export type ComponentCategory =
    | 'clinical'
    | 'admin'
    | 'navigation'
    | 'data-display'
    | 'form'
    | 'feedback'
    | 'layout'
    | 'utility'
    | `custom:${string}`;

// ---------------------------------------------------------------------------
// Nested Data Types (per T11 — standalone named types)
// ---------------------------------------------------------------------------

/**
 * Origin metadata for contracts fetched from federated registries.
 * Populated when a contract is published or discovered remotely.
 */
export type ContractOrigin = {
    /** URL of the remote registry that published this contract. */
    readonly registryUrl: string;
    /** Publisher identifier (e.g., org name or developer handle). */
    readonly publisher: string;
    /** ISO 8601 timestamp when the contract was verified. */
    readonly verifiedAt?: string;
};

/**
 * Internal metadata attached to every contract.
 * Used for DevTools, telemetry, and Forge tracking.
 */
export type ContractMeta = {
    /** Whether this contract was generated by the Forge. */
    readonly forged: boolean;
    /** Semantic version of the contract definition. */
    readonly version: string;
    /** ISO 8601 timestamp when the contract was created. */
    readonly createdAt: string;
};

/**
 * Accessibility configuration for a component.
 * Enforced by the compiler's accessibility audit step.
 */
export type ComponentAccessibility = {
    /** WAI-ARIA role for the component's root element. */
    readonly role: string;
    /** Accessible label describing the component. */
    readonly ariaLabel: string;
    /** Whether screen readers should announce dynamic updates. */
    readonly announceOnUpdate: boolean;
};

/**
 * Data source configuration for adapter-driven data fetching.
 * Optional — components without a data source receive props directly.
 */
export type ComponentDataSource = {
    /** Adapter type used to fetch data (e.g., `'supabase'`, `'firebase'`). */
    readonly adapter: string;
    /** The resource/table/collection to query. */
    readonly resource: string;
    /** Static query parameters merged with runtime params. */
    readonly params?: Readonly<Record<string, unknown>>;
};

/**
 * Auth requirements for rendering a component.
 * When defined, the `AuthAdapter` gates component visibility.
 */
export type ComponentAuth = {
    /** Whether the user must be authenticated to view this component. */
    readonly required: boolean;
    /** Roles permitted to view this component. Empty = any authenticated user. */
    readonly roles: readonly string[];
};

/**
 * Example data for a component contract.
 * Powers the test harness, semantic index warmup, and DevTools previews.
 *
 * @see Design Choice R10
 */
export type ComponentExample = {
    /** Machine-readable canonical intent query for this component. */
    readonly intent: string;
    /** Example props matching the component's schema. */
    readonly props: Readonly<Record<string, unknown>>;
};

/**
 * Lifecycle state renderers — each component must declare placeholder
 * content for all four lifecycle states.
 *
 * @see Principle L9
 */
export type ComponentStates = {
    /** Renderer key or content for the loading state. */
    readonly loading: string;
    /** Renderer key or content for the error state. */
    readonly error: string;
    /** Renderer key or content for the empty state. */
    readonly empty: string;
    /** Renderer key or content for the ready state. */
    readonly ready: string;
};

// ---------------------------------------------------------------------------
// ComponentContract Type
// ---------------------------------------------------------------------------

/**
 * The canonical data shape for a registered Enterstellar component.
 *
 * A `ComponentContract` is the "API surface" of a UI component within the
 * Enterstellar ecosystem. It declares the component's schema (via Zod), semantics,
 * accessibility requirements, design tokens, and lifecycle states.
 *
 * **Important:** This type has NO `render` field. Rendering is decoupled
 * from the contract and handled by platform-specific renderers (L15, R6).
 *
 * @see Bible §3.1
 */
export type ComponentContract = {
    /** PascalCase component name, unique within the registry. */
    readonly name: string;
    /** Branded component identifier derived from the name. */
    readonly id: ComponentId;
    /** Concise human-readable description. Max 120 characters (R2). */
    readonly description: string;
    /** Component category for classification and Forge routing. */
    readonly category: ComponentCategory;
    /** Semantic tags for fuzzy matching. Overlap between components is expected (R12). */
    readonly tags: readonly string[];
    /**
     * Zod schema defining the component's prop interface.
     * Used by the compiler for validation and self-correction.
     */
    readonly props: z.ZodType;
    /** Design tokens referenced by this component. Values are symbolic (e.g., `'token:danger'`). */
    readonly tokens: Readonly<Record<string, string>>;
    /** Accessibility configuration. Enforced by the compiler. */
    readonly accessibility: ComponentAccessibility;
    /** Lifecycle state renderers. All four states are required (L9). */
    readonly states: ComponentStates;
    /** Example data for testing, warmup, and previews. */
    readonly examples: readonly ComponentExample[];
    /** Optional data source configuration for adapter-driven fetching. */
    readonly dataSource?: ComponentDataSource;
    /** Optional auth requirements for gating component visibility. */
    readonly auth?: ComponentAuth;
    /** Optional origin metadata for federated/remote contracts. */
    readonly origin?: ContractOrigin;
    /** Internal metadata for DevTools and telemetry. */
    readonly _meta: ContractMeta;
};

// ---------------------------------------------------------------------------
// Zod Schema
// ---------------------------------------------------------------------------

/**
 * Zod schema for validating `ComponentContract` data at runtime.
 *
 * Used by consumers to validate contracts fetched from remote registries,
 * and internally by `@enterstellar-ai/registry` during registration.
 *
 * @see Design Choice T7
 */
export const ComponentContractSchema = z.object({
    name: z.string().min(1, 'Component name is required.'),
    id: z.string().min(1, 'Component ID is required.'),
    description: z
        .string()
        .min(1, 'Description is required.')
        .max(120, 'Description must be 120 characters or fewer (R2).'),
    category: z.string().min(1, 'Category is required.'),
    tags: z.array(z.string()).min(1, 'At least one tag is required (R3).'),
    props: z.unknown(),
    tokens: z.record(z.string(), z.string()),
    accessibility: z.object({
        role: z.string().min(1, 'Accessibility role is required.'),
        ariaLabel: z.string().min(1, 'Accessibility ariaLabel is required.'),
        announceOnUpdate: z.boolean(),
    }),
    states: z.object({
        loading: z.string().min(1),
        error: z.string().min(1),
        empty: z.string().min(1),
        ready: z.string().min(1),
    }),
    examples: z.array(
        z.object({
            intent: z.string().min(1),
            props: z.record(z.string(), z.unknown()),
        }),
    ),
    dataSource: z
        .object({
            adapter: z.string().min(1),
            resource: z.string().min(1),
            params: z.record(z.string(), z.unknown()).optional(),
        })
        .optional(),
    auth: z
        .object({
            required: z.boolean(),
            roles: z.array(z.string()),
        })
        .optional(),
    origin: z
        .object({
            registryUrl: z.url(),
            publisher: z.string().min(1),
            verifiedAt: z.string().optional(),
        })
        .optional(),
    _meta: z.object({
        forged: z.boolean(),
        version: z.string().min(1),
        createdAt: z.string().min(1),
    }),
});
